blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /
    requirements:
        _locale: es|en|ca


# rutas:
#     resource: "@AppBundle/Resources/config/routing.yml"
#     prefix: /

# app:
#     resource: "@AppBundle/Controller/"
#     type:     annotation
