# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        BlogBundle\Entity\User: bcrypt
            #algorithm: bcrypt
            #cost: 4
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: BlogBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: true
                default_target_path: /index
            logout:
                path: /logout
                target: /login
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        - { path: ^/tags/add, roles: ROLE_ADMIN}
        - { path: ^/tags/edit, roles: ROLE_ADMIN}
        - { path: ^/tags/delete, roles: ROLE_ADMIN}
        - { path: ^/categories/add, roles: ROLE_ADMIN}
        - { path: ^/categories/edit, roles: ROLE_ADMIN}
        - { path: ^/categories/delete, roles: ROLE_ADMIN}
        - { path: ^/entries/add, roles: ROLE_ADMIN}
        - { path: ^/entries/edit, roles: ROLE_ADMIN}
        - { path: ^/entries/delete, roles: ROLE_ADMIN}
        - { path: ^/pages/add, roles: ROLE_ADMIN}
        - { path: ^/pages/edit, roles: ROLE_ADMIN}
        - { path: ^/pages/delete, roles: ROLE_ADMIN}
        - { path: ^/users, roles: ROLE_ADMIN}
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
