# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        BlogBundle\Entity\User: bcrypt
        #FOS\UserBundle\Model\UserInterface: bcrypt
            #algorithm: bcrypt
            #cost: 4
    role_hierarchy:
        ROLE_USER:       ROLE_BECARIO
        ROLE_ADMIN:       [ROLE_USER, ROLE_BECARIO]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_USER, ROLE_BECARIO]
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        # fos_userbundle:
        #     id: fos_user.user_provider.username
        our_db_provider:
            entity:
                class: BlogBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            provider: our_db_provider
            form_login:
                #provider: fos_userbundle
                #csrf_token_generator: security.csrf.token_manager
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: blog_homepage
            logout:
                path: logout
                target: login
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            access_denied_url: error403

    access_control:
        - { path: ^/(es|en|ca)/users/add, roles: ROLE_SUPER_ADMIN}
        - { path: ^/(es|en|ca)/tags/add, roles: ROLE_ADMIN}
        - { path: ^/(es|en|ca)/tags/edit, roles: ROLE_ADMIN}
        - { path: ^/(es|en|ca)/tags/delete, roles: ROLE_ADMIN}
        - { path: ^/(es|en|ca)/categories/add, roles: ROLE_ADMIN}
        - { path: ^/(es|en|ca)/categories/edit, roles: ROLE_ADMIN}
        - { path: ^/(es|en|ca)/categories/delete, roles: ROLE_ADMIN}
        - { path: ^/(es|en|ca)/entries/add, roles: ROLE_ADMIN}
        - { path: ^/(es|en|ca)/entries/edit, roles: ROLE_ADMIN}
        - { path: ^/(es|en|ca)/entries/delete, roles: ROLE_ADMIN}
        - { path: ^/(es|en|ca)/pages/add, roles: ROLE_ADMIN}
        - { path: ^/(es|en|ca)/pages/edit, roles: ROLE_ADMIN}
        - { path: ^/(es|en|ca)/pages/delete, roles: ROLE_ADMIN}
        - { path: ^/(es|en|ca)/users, roles: ROLE_ADMIN}

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
