#################### COMMON ########################
blog_homepage:
    path:     /{_locale}/{page}
    defaults: { _controller: BlogBundle:Entry:index, page: 1, _locale: es }
    requirements:
        _locale:  es|en|ca
        page: '\d+'

login:
    path: /{_locale}/login
    defaults: { _controller: BlogBundle:User:login, _locale: es }
    
login_check:
    path: /login_check
    
logout:
    path: /logout

error403:
    path: /{_locale}/error403
    defaults: { _controller: BlogBundle:Security:denied, _locale: es }

#################### TAG ########################
blog_tag:
    resource: "@BlogBundle/Resources/config/routing/tag.yml"
    prefix:   /

#################### CATEGORY ########################
blog_category:
    resource: "@BlogBundle/Resources/config/routing/category.yml"
    prefix:   /

#################### ENTRY ########################
blog_entry:
    resource: "@BlogBundle/Resources/config/routing/entry.yml"
    prefix:   /

#################### USER ########################
blog_user:
    resource: "@BlogBundle/Resources/config/routing/user.yml"
    prefix:   /

#################### PAGE ########################
blog_page:
    resource: "@BlogBundle/Resources/config/routing/page.yml"
    prefix:   /

#################### COMMENT ########################
blog_comment:
    resource: "@BlogBundle/Resources/config/routing/comment.yml"
    prefix:   /
