services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     functions:
        class: BlogBundle\Functions\Functions
        public: true
