services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     functions:
        class: BlogBundle\Functions\Functions
        public: true

     twig_filters:
        class: BlogBundle\Twig\CustomFilters
        public: true
        tags:
            - { name: twig.extension }
