services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    functions:
        class: BlogBundle\Functions\Functions
        public: true

    twig_filters:
        class: BlogBundle\Twig\CustomFilters
        public: true
        tags:
            - { name: twig.extension }

    app.locale_listener:
        class: BlogBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_suscriber }

    mail_helper:
        class: BlogBundle\Controller\MailerController
        arguments: ['@mailer']
        calls:
        - [setContainer, ["@service_container"]]