# src/BlogBundle/Resources/config/validation.yml
BlogBundle\Entity\Entry:
    properties:
            title:
                - NotBlank: {message: "El titulo no puede estar vacío"}
                - Length:
                    min: 2
                    minMessage: "El titulo tiene que tener mas de 2 caracteres"
            content:
                - NotBlank: {message: "El texto no puede estar vacío"}

BlogBundle\Entity\Tag:
    properties:
            name:
                - NotBlank: {message: "El nombre es necesario"}
                - Length:
                    min: 2
                    minMessage: "El nombre tiene que tener mas de 2 caracteres"

BlogBundle\Entity\Category:
    properties:
            name:
                - NotBlank: {message: "El nombre no puede estar vacío"}
                - Length:
                    min: 2
                    minMessage: "El nombre tiene que tener mas de 2 caracteres"

BlogBundle\Entity\User:
    properties:
            password:
                - NotBlank: {message: "La contraseña no puede estar vacía"}
                - Length:
                    min: 2
                    minMessage: "La contraseña debe que tener más de 5 caracteres"
            email:
                - NotBlank: {message: "El email no puede estar vacío."}
                - Email: {message: "El email {{ value }} no es válido." }
                #     checkMX: true
            roles:
                - NotBlank: {message: "Debes seleccionar al menos un rol."}

BlogBundle\Entity\Comment:
    properties:
            content:
                - NotBlank: {message: "El comentario no puede estar vacío"}
                - Length:
                    min: 5
                    minMessage: "El comentario debe que tener mas de 50 caracteres"